### ISSUE TITLE
Instance member 'cancelCompression' can't be accessed using static access

### ISSUE THREAD

**Issue by Princeyyyy** [mbfakourii/full_picker#11]
Hey, your package is wonderful and has been a great asset to my project. The issue is that the package refuses my project to run because of the above mentioned error: 

```dart
Instance member 'cancelCompression' can't be accessed using static access
```

 I've done research into your package and found that the issue is in the `common_utils.dart` file, specifically: 

```dart
final PercentProgressDialog progressDialog = PercentProgressDialog(
  context,
  (final void value) {
    if (onProgress.value.toString() != '1.0') {
      LightCompressor.cancelCompression();
    }
  },
  onProgress,
  globalFullPickerLanguage.onCompressing,
);
```

I found the solution is to change the above to:
```dart
final LightCompressor compressor =
    LightCompressor(); // Create an instance of LightCompressor
final PercentProgressDialog progressDialog = PercentProgressDialog(
  context,
  (final void value) {
    if (onProgress.value.toString() != '1.0') {
      compressor.cancelCompression(); // Call the method on the instance
    }
  },
  onProgress,
  globalFullPickerLanguage.onCompressing,
);
```

I think you should include it in an update so that everyone can enjoy the package.

Thanks ❤️

**Comment by mbfakourii** [comment]
Thanks for opening this issue.
This bug has been [fixed](https://github.com/mbfakourii/full_picker/commit/8cc055ff3fa98dc4fd98a51e631bb1a159ad3fb6).

**Comment by Princeyyyy** [comment]
Thank you
