### ISSUE TITLE
Implementation guide

### ISSUE THREAD

**Issue by DevanshiGor** [mbfakourii/full_picker#9]
How can i be able to save or upload selected file types in dart code? you have just shown info on screen only.I am a fresher, so unable to implement it in a way that it should upload / save selected file in dart code. it would be great if you can please guide me.

**Comment by mbfakourii** [comment]
Hello, thank you for opening this issues.
This package is only used for file selection. For uploading, you can send and upload the selected file from this package to the server with packages such as [dio](https://pub.dev/packages/dio) or [http](https://pub.dev/packages/http) or [uno](https://pub.dev/packages/uno)
